name: hello-world
on: 
  push:
jobs:
  my-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run --prefix xmcl-keystone-ui build
      - name: BuildAll
        run: pnpm run --prefix xmcl-electron-app build:all
