name: Build
on: 
  push:
jobs:
  my-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check Python version
        run: python --version

      - name: Install Python development headers
        if: matrix.os == 'ubuntu-latest'  # Only install on Ubuntu
        run: sudo apt-get install python3-dev

      - name: Install better-sqlite3
        run: npm install better-sqlite3 --python=python3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Update the version according to your requirement

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: my-step
        run: echo "Hello World!"
