name: hello-world
on: 
  push:
jobs:
  my-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: my-step
        run: echo "Hello World!"