name: Build
on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check Python version
        if: matrix.os != 'windows-latest'  # Skip this step on Windows
        run: python --version

      - name: Check Python version
        if: matrix.os == 'windows-latest'  # Only run on Windows
        run: python --version || echo "Python is not installed"

      - name: Install Python development headers
        if: matrix.os != 'windows-latest'  # Skip this step on 
