name: Test

on:
  push:
    branches:
      - master
    paths:
      - 'xmcl-runtime/**'
      - 'xmcl-runtime-api/**'
      - 'xmcl-keystone-ui/**'
      - 'xmcl-electron-app/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/**'

 #env:
 #  ELECTRON_CACHE: ~/.cache/electron
 #  ELECTRON_BUILDER_CACHE: ~/.cache/electron-builder

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        package-manager: 'pnpm'
      
    - name: Install dependencies
      run: pnpm install
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 8.3.0
    - name: Fix node-gyp and Python
      run: python3 -m pip install packaging setuptools
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install
      run: pnpm install
    - name: Build
      run: echo "test"