name: hello-world
on: 
  push:
jobs:
  my-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: pnpminstall
        run: npm install pnpm
      - name: Install
        run: pnpm install
      - name: Render
        run: pnpm build:renderer
      - name: Build
        run: pnpm build:all
